service: MenRoute
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs18.x
  stage: ${opt:stage, 'dev'}
  environment:
    DYNAMODB_MENS_TABLE: ${self:service}-mensTable-${sls:stage}
  iam:
    role:
      statements:
        - Effect: "Allow"
          Action:
            - "dynamodb:PutItem"
            - "dynamodb:Get*"
            - "dynamodb:Scan*"
            - "dynamodb:UpdateItem"
            - "dynamodb:DeleteItem"
          Resource: arn:aws:dynamodb:${aws:region}:${aws:accountId}:table/${self:service}-mensTable-${sls:stage}

resources:
  Resources:
    MensTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: primary_key
            AttributeType: S
        BillingMode: PAY_PER_REQUEST
        KeySchema:
          - AttributeName: primary_key
            KeyType: HASH
        TableName: ${self:service}-mensTable-${sls:stage}

functions:
  createMen:
    handler: src/handlers/createMen.createMen
    events:
      - httpApi:
          path: /mens
          method: post
  getMens:
    handler: src/handlers/getMens.getMens
    events:
      - httpApi:
          path: /getmens
          method: get
